version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "nography"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-18wauojf7m9b5"
s3_prefix = "nography"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
image_repositories = ["ExposeFunction=532688539985.dkr.ecr.eu-central-1.amazonaws.com/nography"]
