AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.8

  SAM Template for nography

Globals:
  Function:
    Timeout: 60

Resources:
  HideFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hide/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        Hide:
          Type: Api
          Properties:
            Path: /hide
            Method: post
      Policies:
      - Statement:
        - Effect: "Allow" 
          Action: 
            - 'lambda:GetLayerVersion' 
          Resource: 
            - 'arn:aws:lambda:*:532688539985:layer:*:*'
      Layers:
        - arn:aws:lambda:eu-central-1:532688539985:layer:error_correction:1
  ExposeFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 2048  # TODO: do we need more memory or is this sufficient?
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./expose
      DockerTag: python3.8-v1
  ErrorCorrection:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: error_correction
      Description: Error Correction
      ContentUri: ./error_correction
      CompatibleRuntimes:
        - python3.8
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: makefile

Outputs:
  HideApi:
    Description: "API Gateway endpoint URL for Prod stage for Hide function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hide/"
  HideFunction:
    Description: "Hide Lambda Function ARN"
    Value: !GetAtt HideFunction.Arn
  HideFunctionIamRole:
    Description: "Implicit IAM Role created for Hide function"
    Value: !GetAtt HideFunctionRole.Arn

  ExposeApi:
    Description: "API Gateway endpoint URL for Prod stage for Expose function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/expose/"
  ExposeFunction:
    Description: "Expose Lambda Function ARN"
    Value: !GetAtt ExposeFunction.Arn
  ExposeFunctionIamRole:
    Description: "Implicit IAM Role created for Expose function"
    Value: !GetAtt ExposeFunctionRole.Arn