AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.8

  SAM Template for nography

Globals:
  Function:
    Timeout: 3

Resources:
  HideFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hide/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        Hide:
          Type: Api
          Properties:
            Path: /hide
            Method: get
  FrontendFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: frontend/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        GetHtml:
          Type: Api
          Properties:
            Path: /
            Method: get
        PostForm:
          Type: Api
          Properties:
            Path: /
            Method: post
        

Outputs:
  HideApi:
    Description: "API Gateway endpoint URL for Prod stage for Hide function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hide/"
  HideFunction:
    Description: "Hide Lambda Function ARN"
    Value: !GetAtt HideFunction.Arn
  HideFunctionIamRole:
    Description: "Implicit IAM Role created for Hide function"
    Value: !GetAtt HideFunctionRole.Arn
  FrontendApi:
    Description: "API Gateway endpoint URL for Prod stage for Frontend function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  FrontendFunction:
    Description: "Frontend Lambda Function ARN"
    Value: !GetAtt FrontendFunction.Arn
  FrontendFunctionIamRole:
    Description: "Implicit IAM Role created for Frontend function"
    Value: !GetAtt FrontendFunctionRole.Arn