build-ErrorCorrection:
	# Copies the files for the Hide Lambda
	mkdir -p "$(ARTIFACTS_DIR)/python"
	cp *.py "$(ARTIFACTS_DIR)/python"
	# Copies the files for the Expose Lambda
	mkdir -p "$(ARTIFACTS_DIR)/../../../expose/app/error_correction"
	cp *.py "$(ARTIFACTS_DIR)/../../../expose/app/error_correction"
	